name: flutter_book_geolocation
description: "flutter_book_geolocation"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider:
  sqflite:
  path_provider:
  flutter_slidable:
  intl:
  image_picker:
  flutter_calendar_carousel:
  cupertino_icons:
  geolocator:
  geocoding:
  google_maps_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


